speaking_club/apps/individual_lessons/urls.py
from django.contrib import admin
from . import views
from django.urls import path

urlpatterns = [
    path("<str:gc_user>/", views.index, name="individual_lessons_index"),
    path("<str:gc_user>/date/", views.get_date, name="individual_lessons_get_date"),
    path(
        "<str:gc_user>/change_teacher/",
        views.change_teacher,
        name="individual_lessons_change_teacher",
    ),
    path(
        "<str:gc_user>/delete_lesson/",
        views.delete_lesson,
        name="individual_lessons_delete_lesson",
    ),
]


urlpatterns += [
    path(
        "teacher/<str:gc_user>/",
        views.index_teacher,
        name="individual_lessons_index_teacher",
    ),
    path(
        "teacher/<str:gc_user>/change_lessons/",
        views.change_lessons,
        name="individual_lessons_change_lessons_teacher",
    ),
]

speaking_club/speaking_club/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView, RedirectView
from django.urls import reverse_lazy
from django.conf import settings
from django.conf.urls.static import static

from apps.speaking_clubs.views import login


urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('social_django.urls', namespace='social')),
    # path('robokassa/', include('robokassa.urls')),
    path('speaking_club/', include('speaking_clubs.urls')),
    path('individual_lessons/', include('individual_lessons.urls')),
    path('login/', login, name='login'),
    path('', RedirectView.as_view(url=reverse_lazy('main_gc'))),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

speaking_club/apps/individual_lessons/models.py
from django.db import models
from django.utils import timezone

from speaking_clubs.models import Level, Student


class IndividualLevel(models.Model):
    name = models.CharField(
        'Уровень',
        max_length=255,
    )

    def __str__(self) -> str:
        return self.name

    class Meta:
        verbose_name = 'Уровень'
        verbose_name_plural = 'Уровни'


class IndividualTopic(models.Model):
    name = models.CharField(
        'Название',
        max_length=255,
    )

    level = models.ForeignKey(
        Level,
        on_delete=models.CASCADE,
        verbose_name='Уровень',
        null=False,
        blank=False,
    )

    def __str__(self) -> str:
        return f"{self.name}"

    class Meta:
        verbose_name = 'Тема'
        verbose_name_plural = 'Темы'


class IndividualTeacher(models.Model):
    gc_user = models.IntegerField(
        'ID с GetCourse',
    )

    first_name = models.CharField(
        'Имя',
        max_length=255,
    )

    last_name = models.CharField(
        'Фамилия',
        max_length=255,
    )

    photo = models.ImageField(
        'Фото профиля',
        upload_to='individual_lessons/img/teacher_photo',
        null=False,
        blank=False,
    )

    zoom_key = models.CharField(
        'Ключ Zoom',
        max_length=500,
    )
    zoom_sec = models.CharField(
        'Секретный ключ Zoom',
        max_length=500,
    )
    zoom_client = models.CharField(
        'Client ID Zoom',
        max_length=500,
    )

    def __str__(self) -> str:
        return " ".join((el for el in (self.first_name, self.last_name) if el))

    class Meta:
        verbose_name = 'Преподаватель'
        verbose_name_plural = 'Преподаватели'


class IndividualStudent(models.Model):
    gc_user = models.IntegerField(
        'ID с GetCourse',
    )

    student = models.OneToOneField(
        Student,
        on_delete=models.CASCADE,
        verbose_name='Ученик',
    )

    hours_paid = models.PositiveIntegerField(
        'Занятий оплачено',
        default=0,
        blank=False,
        null=False,
    )

    teacher = models.ForeignKey(
        IndividualTeacher,
        on_delete=models.CASCADE,
        verbose_name='Преподаватель',
        null=True,
        blank=True,
    )

    def __str__(self) -> str:
        return f"{self.first_name}"

    @property
    def level(self) -> str:
        return self.student.get_user_level()

    @property
    def first_name(self) -> str:
        return self.student.name

    class Meta:
        verbose_name = 'Ученик'
        verbose_name_plural = 'Ученики'


class IndividualLesson(models.Model):
    status = models.CharField(
        "Статус",
        max_length=255,
        blank=False,
        null=False,
        choices=(
            ("Создан", "Создан"),
            ("Почти отменен", "Почти отменен"),
            ("Забронирован", "Забронирован"),
        ),
        default="Создан",
    )
    date = models.DateField(
        'Дата',
        blank=False,
        null=False,
    )

    time = models.TimeField(
        'Время',
        blank=False,
        null=False,
    )

    teacher = models.ForeignKey(
        IndividualTeacher,
        on_delete=models.CASCADE,
        verbose_name='Преподаватель',
        null=True,
        blank=True,
    )

    student = models.ForeignKey(
        IndividualStudent,
        on_delete=models.CASCADE,
        verbose_name='Ученик',
        null=True,
        blank=True,
    )

    topic = models.ForeignKey(
        IndividualTopic,
        on_delete=models.CASCADE,
        verbose_name='Тема',
        null=True,
        blank=True,
    )

    zoom_id = models.CharField(
        'ID встречи',
        blank=True,
        null=True,
        max_length=50,
    )
    zoom_url = models.URLField(
        'Ссылка на встречу',
        blank=True,
        null=True,
    )
    zoom_password = models.CharField(
        'Пароль встречи',
        max_length=20,
        blank=True,
        null=True,
    )

    def datetime(self) -> timezone.datetime:
        return timezone.datetime(
            year=self.date.year,
            month=self.date.month,
            day=self.date.day,
            hour=self.time.hour,
            minute=self.time.minute,
            second=self.time.second,
            microsecond=self.time.microsecond,
        )

    class Meta:
        verbose_name = 'Занятие'
        verbose_name_plural = 'Занятия'

speaking_club/apps/individual_lessons/views.py
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpRequest, JsonResponse, HttpResponseBadRequest
from django.shortcuts import redirect, render
from django.urls import reverse
from django.utils import timezone
from django.contrib import messages

from django.db.models import Count, ExpressionWrapper, F, DateTimeField
from django.db.models.functions import TruncDate

from individual_lessons.forms import (
    IndividualLessonCreateForm,
    IndividualLessonForm,
    ChangeTeacherForm,
    IndividualLessonTeacherForm,
)
from individual_lessons.models import (
    IndividualLesson,
    IndividualStudent,
    IndividualTeacher,
)
from individual_lessons.helpers import create_meeting, delete_meeting

import logging


SHEDULE = [
    "8:00",
    "8:35",
    "9:10",
    "9:45",
    "10:20",
    "10:55",
    "11:30",
    "12:35",
    "13:10",
    "13:45",
    "14:20",
    "14:55",
    "15:30",
    "16:05",
    "16:40",
    "17:15",
    "17:50",
    "18:25",
    "19:00",
    "19:35",
]

SHEDULE = [timezone.datetime.strptime(el, "%H:%M").time() for el in SHEDULE]


@csrf_exempt
def index(request: HttpRequest, gc_user: str):
    student = IndividualStudent.objects.filter(
        gc_user=gc_user,
    ).first()
    if student:
        if student.level in (None, "-"):
            return render(
                request,
                "individual_lessons/redirect.html",
                {
                    "header": "Сначала пройдите тестирование",
                    "url": reverse("profile_test_results"),
                },
            )

        if request.method == "POST":
            if student.hours_paid > 0:
                form = IndividualLessonCreateForm(request.POST)

                if form.is_valid():
                    # form.save()
                    lesson = IndividualLesson.objects.filter(
                        date=form.cleaned_data.get("date"),
                        time=form.cleaned_data.get("time"),
                        teacher=student.teacher,
                        student=None,
                    ).first()
                    if not lesson:
                        logging.warning(f"add_lesson: error 1 {form.cleaned_data=}")
                        messages.error(request, "Не удалось создать занятие")
                    else:
                        if (
                            IndividualLesson.objects.filter(
                                date=form.cleaned_data.get("date"),
                                student=student,
                            ).count()
                            >= 4
                        ):
                            logging.warning("add_lesson: error 2")
                            messages.error(
                                request, f"Нельзя забронировать больше 4 занятий в день"
                            )
                        elif (
                            lesson.date == timezone.now().date()
                            and lesson.time
                            <= (timezone.now() + timezone.timedelta(minutes=15)).time()
                        ):
                            logging.warning("add_lesson: error 3")
                            messages.error(request, "Не удалось создать занятие")
                        else:
                            lesson.student = student
                            lesson.teacher = student.teacher
                            lesson.topic = form.cleaned_data.get("topic")
                            lesson.status = "Забронирован"
                            meeting = create_meeting(student, lesson)
                            if meeting and meeting.get("status") != 1:
                                logging.warning(f"{meeting=}")
                                messages.error(
                                    request, "Не удалось создать занятие в Zoom"
                                )
                            else:
                                lesson.zoom_url = meeting["meeting_url"]
                                lesson.zoom_password = meeting["password"]
                                lesson.zoom_id = meeting["id"]
                                lesson.save()

                                student.hours_paid -= 1
                                student.save()
                                messages.success(request, f"Занятие забронировано")
                else:
                    logging.warning(f"{form.errors}")
            else:
                messages.error(request, f"Оплатите еще занятия")

        form = IndividualLessonCreateForm(
            initial={
                "student": student,
                "teacher": student.teacher,
            }
        )

        my_lessons = (
            IndividualLesson.objects.filter(
                student=student,
                date__gte=timezone.now().date(),
            )
            .annotate(
                _datetime=ExpressionWrapper(
                    F("date") + F("time"),
                    output_field=DateTimeField(),
                )
            )
            .filter(
                _datetime__gt=timezone.now(),
                _datetime__lt=timezone.now() + timezone.timedelta(days=1),
            )
            .order_by("_datetime")
            .all()
        )

        # my_lessons = [el for el in my_lessons if el.datetime() >= timezone.now()]

        my_lessons = [IndividualLessonForm(instance=el) for el in my_lessons]

        change_teacher_form = ChangeTeacherForm(instance=student)

        today = timezone.now()
        day_of_week = today.weekday()
        start_of_week = today - timezone.timedelta(days=day_of_week)
        end_of_week = start_of_week + timezone.timedelta(days=21)

        date_list = (
            IndividualLesson.objects.filter(
                date__range=(start_of_week, end_of_week),
                student=None,
                teacher=student.teacher,
            )
            .values("date")
            .annotate(lesson_count=Count("id"))
            .order_by("date")
            .values_list("date", flat=True)
        )

        date_list = [el for el in date_list]

        calendar = []

        all_dates = [
            start_of_week.date() + timezone.timedelta(days=i) for i in range(21)
        ]

        logging.warning(f"{date_list=}")

        for lesson_date in all_dates:
            lessons_on_date = []
            if lesson_date in date_list:
                lessons_on_date = (
                    IndividualLesson.objects.filter(
                        date=lesson_date,
                        student=None,
                        teacher=student.teacher,
                    )
                    .annotate(
                        _datetime=ExpressionWrapper(
                            F("date") + F("time"),
                            output_field=DateTimeField(),
                        )
                    )
                    .order_by("_datetime")
                )

            calendar.append(
                {
                    "lesson_date": lesson_date,
                    "lessons_on_date": lessons_on_date,
                }
            )

        # logging.warning(f"{calendar=}")
        return render(
            request,
            "individual_lessons/index.html",
            {
                "form": form,
                "my_lessons": my_lessons,
                "gc_user": gc_user,
                "calendar": calendar,
                "now": timezone.now(),
                "change_teacher_form": change_teacher_form,
                "student": student,
            },
        )
    else:
        return render(
            request,
            "individual_lessons/redirect.html",
            {"header": "Сначала пройдите регистрацию", "url": reverse("main_gc")},
        )


@csrf_exempt
def get_date(request: HttpRequest, gc_user: str):
    if request.method == "GET":
        student = IndividualStudent.objects.filter(
            gc_user=gc_user,
        ).first()
        date = request.GET.get("date")
        try:
            date = timezone.datetime.strptime(date, "%Y-%m-%d").date()
        except Exception as err:
            logging.error(err)
            date = None

        if (
            all((student, date))
            and student.teacher
            and (
                timezone.now().date()
                <= date
                <= timezone.now().date() + timezone.timedelta(days=14)
            )
        ):
            lessons = (
                IndividualLesson.objects.filter(
                    date=date,
                    teacher=student.teacher,
                    student=None,
                )
                .annotate(
                    _datetime=ExpressionWrapper(
                        F("date") + F("time"),
                        output_field=DateTimeField(),
                    )
                )
                .order_by("_datetime")
                .annotate(
                    _datetime=ExpressionWrapper(
                        F("date") + F("time"),
                        output_field=DateTimeField(),
                    )
                )
                .order_by("_datetime")
            )
            if date == timezone.now().date():
                lessons = lessons.filter(
                    time__gt=((timezone.now() + timezone.timedelta(minutes=15)).time()),
                )
            lessons = lessons.all()
            available_time = [el.time.strftime("%H:%M") for el in lessons]

            return JsonResponse(
                {
                    "available_time": available_time,
                }
            )
        else:
            logging.error(
                f"{student=}, {date.isoformat()=}, {student.teacher=}, {timezone.now().date() <= date <= (timezone.now().date() + timezone.timedelta(days=14))}"
            )
        student.teacher.photo.path
    return JsonResponse(
        {
            "available_time": [],
        }
    )


@csrf_exempt

speaking_club/templates/individual_lessons/index.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}


{% load custom_filters %}

{% block title %}
Индивидуальные уроки
{% endblock %}

{% block content %}

<div class="container my-5">
    <div class="row">
        <div class="col-12 col-md-6 d-flex flex-column justify-content-center align-items-center align-items-md-start">
            <h1>{% now "F Y" %}</h1>
            <h4>Ваше текущее время: {% now "H:i" %} МСК</h4>
            <h4>Осталось занятий: {{student.hours_paid}}</h4>
            <!-- <h4><a href="">Получать уведомления в telegram</a></h4> -->
        </div>
        <div class="col-12 col-md-6 mt-2 mt-md-0">
            <div class="d-flex gap-3 align-items-end">
                <div class="col-6 d-flex justify-content-end">
                    <img src="{{student.teacher.photo.url}}" alt="" class="img-fluid rounded-3">
                </div>
                <div class="col-6">
                    <h4>Ваш преподаватель</h4>
                    <h2>{{student.teacher}}</h2>

                    <h4>
                        <button class="btn btn-primary" type="button" data-bs-toggle="collapse"
                            data-bs-target="#changeTeacher" aria-expanded="false" aria-controls="changeTeacher">
                            <i class="bi bi-chevron-down"></i> Выбрать другого
                        </button>
                    </h4>
                </div>
            </div>

            <div class="collapse mt-3" id="changeTeacher">
                <div class="card card-body">
                    <form method="post" action="{% url 'individual_lessons_change_teacher' gc_user %}">
                        {% csrf_token %}
                        {{ change_teacher_form|crispy }}
                        <button type="submit" class="btn btn-primary w-100 mx-1">Сохранить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="container my-5">
    <div id="new-lesson">
        <p class="d-inline-flex gap-1 w-md-100">
            <a class="btn btn-primary fs-4 px-4 w-md-100" data-bs-toggle="collapse" href="#newLesson" role="button"
                aria-expanded="false" aria-controls="newLesson" id="new-lesson-btn">
                + Добавить урок
            </a>
        </p>
        <div class="collapse container bg-white p-3 rounded-3" id="newLesson">
            <form method="post">
                {% csrf_token %}
                <div class="d-xl-flex gap-xl-4">
                    {{ form|crispy }}
                </div>
                <div class="d-flex">
                    <button type="submit" class="btn btn-color-save w-100 mx-1">Сохранить</button>
                    <a class="btn btn-color-cancel w-100 mx-1" onclick="window.location.reload()">Отменить</a>
                </div>
            </form>
        </div>
    </div>
</div>


<div class="container my-5" id="myLessons">
    {% if my_lessons %}
    <h1>Ваши ближайшие занятия</h1>

    {% for les in my_lessons %}
    <div class="container my-4">
        <form method="post" action="{% url 'individual_lessons_delete_lesson' gc_user %}" class="row">
            {% csrf_token %}
            <div class="col-12 col-xl-10 bg-white p-3 rounded-3">
                <div class="d-xl-flex gap-xl-4">
                    {{ les|crispy }}
                </div>
            </div>
            <div class="col-12 col-xl-2 mt-2 mt-xl-0 d-flex gap-2 lessonsBtn d-flex align-items-center">
                <button class="btn text-white fs-4" style="background-color: #BD9F8F;" type="submit">
                    <i class="bi bi-x-lg"></i>
                </button>
                <a class="btn btn-primary fs-4 w-100 {% if les.date.value|date:'Y-m-d' != now|date:'Y-m-d' %} disabled {% endif %}"
                    href="{{les.zoom_url.value}}">
                    <span class="fs-5">Войти</span>
                </a>
            </div>
        </form>
    </div>
    {% endfor %}
    {% endif %}
</div>

<!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous"> -->


<div class="container">
    <h1>Расписание вашего преподавателя</h1>
</div>
<div class="container my-4 bg-white p-0 p-xl-3 rounded-3">
    <div id="carouselExample" class="carousel slide">
        <div class="carousel-inner">
            <div class="d-flex flex-row gap-3 mb-4 pt-3 p-md-3 justify-content-center justify-content-xl-start">
                <button class="btn fs-4" data-bs-target="#carouselExample" data-bs-slide="prev" disabled>
                    <i class="bi bi-arrow-left-circle-fill text-primary"></i>
                </button>
                <button class="btn fs-4 text-primary" onclick="currentWeek(this)">
                    Сегодня
                </button>
                <button class="btn fs-4" data-bs-target="#carouselExample" data-bs-slide="next">
                    <i class="bi bi-arrow-right-circle-fill text-primary"></i>
                </button>
            </div>
            <div class="carousel-item active">
                <div class="row justify-content-center">
                    {% for data in calendar|slice:":7" %}
                    <div class="text-center col col-calendar">
                        <div>
                            {{ data.lesson_date|date:"D" }}
                            <br>
                            <h3
                                class="p-2 {% if data.lesson_date|date:'Y-m-d' == now|date:'Y-m-d' %}bg-primary rounded-circle text-white today{% endif %}">
                                {{ data.lesson_date|date:"j" }}
                            </h3>
                        </div>

                        {% for lesson in data.lessons_on_date %}
                        {% if lesson.datetime|iso_format_with_colon <= now|iso_format_with_colon and lesson.student == student %}
                        <div class="fs-5 text-secondary">
                            {{lesson.time}}
                        </div>
                        {% elif lesson.datetime|iso_format_with_colon >= now|iso_format_with_colon %}
                        <div class="fs-5">
                            {{lesson.time}}
                        </div>
                        {% endif %}
                        {% endfor %}
                    </div>
                    {% endfor %}
                </div>
            </div>
            <div class="carousel-item">
                <div class="row justify-content-center">
                    {% for data in calendar|slice:"7:14" %}
                    <div class="text-center col col-calendar">
                        <div>
                            {{ data.lesson_date|date:"D" }}
                            <br>
                            <h3 class="p-2">
                                {{ data.lesson_date|date:"j" }}
                            </h3>
                        </div>

                        {% for lesson in data.lessons_on_date %}
                        {% if lesson.datetime|iso_format_with_colon <= now|iso_format_with_colon and lesson.student == student %}
                        <div class="fs-5 text-secondary">
                            {{lesson.time}}
                        </div>
                        {% elif lesson.datetime|iso_format_with_colon >= now|iso_format_with_colon %}
                        <div class="fs-5">
                            {{lesson.time}}
                        </div>
                        {% endif %}
                        {% endfor %}
                    </div>
                    {% endfor %}
                </div>
            </div>
            <div class="carousel-item">
                <div class="row justify-content-center">
                    {% for data in calendar|slice:"14:" %}
                    <div class="text-center col col-calendar">
                        <div>
                            {{ data.lesson_date|date:"D" }}
                            <br>
                            <h3 class="p-2">
                                {{ data.lesson_date|date:"j" }}
                            </h3>
                        </div>

                        {% for lesson in data.lessons_on_date %}
                        {% if lesson.datetime|iso_format_with_colon <= now|iso_format_with_colon and lesson.student == student %}
                        <div class="fs-5 text-secondary">
                            {{lesson.time}}
                        </div>
                        {% elif lesson.datetime|iso_format_with_colon >= now|iso_format_with_colon %}
                        <div class="fs-5">
                            {{lesson.time}}
                        </div>
                        {% endif %}
                        {% endfor %}
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>

    </div>
</div>




<script>
    // $('#newLesson form .mb-3').addClass('w-100');
    // $('#myLessons form .mb-3').addClass('w-100');
    // $('#myLessons form .mb-3').addClass('mb-xl-3');
    // $('#myLessons form .mb-3').addClass('mb-xl-3');

    $('#newLesson form #div_id_time select').on('click', function (e) {
        if ($('#newLesson form #div_id_time select').attr('disabled') == 'disabled') {
            console.log('no time')
        }
    })

    $('#newLesson form #div_id_date input').on('change', function (e) {
        date = $('#newLesson form #div_id_date input').val();
        if (date) {
            console.log(`date=${date}`)
            $.getJSON(
                "{% url 'individual_lessons_get_date' gc_user %}",
                {
                    'date': date,
                },
                function (data) {
                    if (data && data['available_time'].length > 0) {
                        html = "";
                        data['available_time'].forEach(element => {
                            html += `<option value="${element}">${element}</option>\n`
                        });
                        time_select = document.querySelector('#id_time');
                        time_select.innerHTML = html;
                        time_select.disabled = false;
                    } else {
                        // alert('Нет доступного времени для записи');
                    }
                }
            );
        }
    });






    const carouselExampleElement = document.querySelector('#carouselExample')

    const carousel = new bootstrap.Carousel(carouselExampleElement, {
        interval: false,
        wrap: false
    });

    $('#carouselExample').on('slid.bs.carousel', '', function () {
        console.log(this)
        var $this = $(this);

        this.querySelector('.bi-arrow-left-circle-fill').closest('button').disabled = false;
        this.querySelector('.bi-arrow-right-circle-fill').closest('button').disabled = false;

        if (document.querySelector('.carousel-inner .carousel-item').classList.contains('active')) {
            console.log(123)
            this.querySelector('.bi-arrow-left-circle-fill').closest('button').disabled = true;
        } else if (document.querySelector('.carousel-inner .carousel-item:last-child').classList.contains('active')) {
            console.log(1223)
            this.querySelector('.bi-arrow-right-circle-fill').closest('button').disabled = true;
        }

    });


    function currentWeek(btn) {
        console.log('currentWeek');
        carousel.to(0);
    }
</script>


<style>
    #newLesson form .mb-3,
    #myLessons form .mb-3 {
        width: 100%;
        display: flex;
        align-items: center;
    }

    @media (min-width: 1200px) {
        #myLessons form .mb-3 {
            margin-bottom: 0 !important;
        }
    }


    #newLesson form .mb-3 label,
    #myLessons form .mb-3 label {
        margin-bottom: 0;
        margin-right: 1rem;
    }

    #newLesson form .mb-3 input,
    #newLesson form .mb-3 select,
    #myLessons form .mb-3 input,
    #myLessons form .mb-3 select {
        background-color: #E6E6E6;
    }

    #newLesson form .asteriskField,
    #myLessons form .asteriskField {
        display: none;
    }

    .carousel-inner .btn:disabled {
        border-color: transparent !important;
    }

    .carousel-inner .today {
        aspect-ratio: 1/1;
        display: inline-block;
    }

    .img-fluid {
        width: -webkit-fill-available;
        aspect-ratio: 1;
        border-radius: .9rem;
        max-width: 150px;
        max-height: 150px;
    }

    .btn-color-save {
        background-color: #5EBF69;
        color: #FFF;
    }

    .btn-color-cancel {
        background-color: #BD9F8F;
        color: #FFF;
    }

    .col-calendar {
        flex: 0 0 auto;
        width: calc(100% / 7);
    }

    @media (max-width: 1200px) {
        .col-calendar {
            flex: 0 0 auto;
            width: calc(100% / 8);
        }
    }

    @media (max-width: 768px) {
        .w-md-100 {
            width: 100%;
        }

    }
</style>

{% endblock %}

speaking_club/templates/individual_lessons/redirect.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}


{% load custom_filters %}

{% block title %}
Индивидуальные уроки
{% endblock %}

{% block content %}

<div class="container h-100 my-5 bg-white rounded-3 d-flex flex-column justify-content-center align-items-center p-5">
    <h3>{{header}}</h3>
    <button class="btn btn-primary my-3" onclick="window.open('{{url}}', '_blank').focus();">Перейти</button>
</div>

{% endblock %}